CREATE TABLE dados_wokwi (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    distancia_atual_cm FLOAT,
    distancia_anterior_cm FLOAT,
    temperatura FLOAT,
    umidade FLOAT,
    vento_velocidade_ms FLOAT,
    insolacao_h FLOAT,
    evaporacao_piche_mm FLOAT,
    precipitacao_mm FLOAT,
    data_recebimento TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE predicoes (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dados_id NUMBER,
    vazao_prevista FLOAT,
    risco VARCHAR2(20),
    explicabilidade CLOB,
    data_predicao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_predicoes_dados FOREIGN KEY (dados_id) REFERENCES dados_wokwi(id)
);

